projects:
  netflix:
    schemaPath: Users/chaoslegacy/Workspace/Github/ReactNative/Netflix/graphql/schema.json
    includes:
      - /graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: /src/services/API.ts
        docsFilePath: /src/services/graphql
extensions:
  amplify:
    version: 3
